name = "SpatialDependence"
uuid = "011225bf-f2c3-4261-bf98-e88701b28bbe"
authors = ["Javier Barbero and contributors"]
version = "0.4.3"

[deps]
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[weakdeps]
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[extensions]
SpatialDependenceRecipesBaseExt = "RecipesBase"

[compat]
GeoInterface = "1"
NearestNeighbors = "0.4"
PlotUtils = "1"
RecipesBase = "1"
Statistics = "1"
StatsAPI = "1.8"
StatsBase = "0.34"
Tables = "1"
julia = "1.10"

[extras]
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SpatialDatasets = "c34fe46e-cbfb-4865-a11c-95c0a2f62188"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["RecipesBase", "SpatialDatasets", "StableRNGs", "Test"]
